getRecommender<-function(recommendername){
  cmpfun(
    switch(recommendername,
           noneRecommender=function(result_relevent,composite_N,...){
             result_relevent[1:min(length(result_relevent),composite_N)]
           },
           weightedHybridRecommender=weightedHybridRecommend,
           allotHybridRecommender=allothybridRecommend
    ))
}
# recommender control
getRecommendController<-function(controllername){
  cmpfun(
    switch(controllername,
           simpleWeightControl=simpleWeightControl
    ))
}
# sub-measures in every recommender
data(result_LDA_abstarct_gibbs, envir=environment())
getPreferenceEvaluator<-function(name){
  cmpfun(
    switch(name,
           elasticNetPreferenceEval=elasticNetPreferenceEval,
           cosPreferenceEval=cosPreferenceEval
    ))
}
getQualityEvaluator<-function(name){
  cmpfun(
    switch(name,
           citedQualityEval=citedQualityEval,
           SCIImpactFactorEval=SCIImpactFactorEval
    ))
}
getSummaryValueEvaluator<-function(name){
  cmpfun(
    switch(name,
           topicSummaryEval=topicSummaryEval
    ))
}
getFreshEvaluator<-function(name){
  cmpfun(
    switch(name,
           yearDiffReciprocalFreshEval=yearDiffReciprocalFreshEval
    ))
}
getExploreValueEvaluator<-function(name){
  cmpfun(
    switch(name,
           activeExploreEval=activeExploreEval
    ))
}