getRecommender<-function(recommendername){
  cmpfun(
    switch(recommendername,
           noneRecommender=function(result_relevent,composite_N,...){
             result_relevent[1:min(length(result_relevent),composite_N)]
           },
           preferenceOnlyRecommender=preferenceOnlyRecommend,
           exploreHybridRecommender=exploreHybridRecommend,
           weightedHybridRecommender=weightedHybridRecommend,
           allotHybridRecommender=allothybridRecommend
    ))
}
# recommender control
getRecommendController<-function(controllername){
  cmpfun(
    switch(controllername,
           simpleWeightControl=simpleWeightControl,
           hybridWeightControl=hybridWeightControl
    ))
}
# sub-measures in every recommender
data(result_LDA_abstarct_VEM, envir=environment())
getRatingEvaluator<-function(name){
  cmpfun(
    switch(name,
           elasticNetPreferenceEval=elasticNetPreferenceEval,
           cosPreferenceEval=cosPreferenceEval
    ))
}
getQualityEvaluator<-function(name){
  cmpfun(
    switch(name,
           citedQualityEval=citedQualityEval,
           SCIImpactFactorEval=SCIImpactFactorEval
    ))
}
getSummaryValueEvaluator<-function(name){
  cmpfun(
    switch(name,
           topicEntropySummaryEval=topicEntropySummaryEval
    ))
}
getFreshEvaluator<-function(name){
  cmpfun(
    switch(name,
           yearDiffReciprocalFreshEval=yearDiffReciprocalFreshEval
    ))
}
getLearnValueEvaluator<-function(name){
  cmpfun(
    switch(name,
           activeExploreEval=activeExploreEval
    ))
}